Feature/arrays
boskuv/study pull request #1
Opened 2021-11-14 20:18 UTC by boskuv

2021-11-17 08:18 UTC, moklidia requested changes

2021-11-17 08:18 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        array.map! { |el| el.positive? ? max : el }
Лучше не использовать деструктивный метод

2021-11-17 08:18 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +                     array.length / 2 - 1
Достаточно разделить на 2 в любом случае

2021-11-17 08:18 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        if array.include? query
Давай не будем использовать  `.include?`. Мы должны это выяснить с помощью бинарного поиска.

2021-11-18 10:50 UTC, boskuv commented on test/exercise/arrays/solution.rb
> +        array.map! { |el| el.positive? ? max : el }
fixed

2021-11-18 10:50 UTC, boskuv commented on test/exercise/arrays/solution.rb
> +                     array.length / 2 - 1
fixed

2021-11-18 10:50 UTC, boskuv commented on test/exercise/arrays/solution.rb
> +        if array.include? query
fixed

2021-11-19 11:31 UTC, moklidia approved these changes

2021-11-20 19:10 UTC, merged