solve fp task
boskuv/study pull request #2
Opened 2021-11-18 19:24 UTC by boskuv

2021-11-19 11:32 UTC, moklidia requested changes

2021-11-19 11:32 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        filtered_films.map { |film| film['name'].count('и') }.reduce(0) { |a, b| a + b }
А зачем тебе в конце еще дополнительный редьюс?

2021-11-20 10:33 UTC, boskuv commented on test/exercise/fp/solution.rb
> +        filtered_films.map { |film| film['name'].count('и') }.reduce(0) { |a, b| a + b }
Посчитать количесвто букв 'и' в названиях **всех** фильмов с рейтингом кинопоиска больше или равным заданному значению. "map" посчитает для каждого фильма, reduce - просуммирует.

2021-11-22 12:42 UTC, moklidia approved these changes

2021-11-22 12:42 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        filtered_films.map { |film| film['name'].count('и') }.reduce(0) { |a, b| a + b }
Ой, извини, я не увидела.

2021-11-22 16:46 UTC, merged